Adds new outline README
pyladieshamburg/IOTworkshop pull request #13
Opened 2019-11-17 20:54 UTC by sleepypioneer

2019-11-17 20:55 UTC, sleepypioneer commented
**WORK IN PROGRESS**

2021-01-25 12:59 UTC, bwnstck requested changes
Fixes some links

2021-01-25 12:59 UTC, bwnstck commented on README.md
> +For setting up the raspberry Pi follow the instructions in [0_pi-setup](pi-setup/initial-setup.md)
```suggestion
For setting up the raspberry Pi follow the instructions in [0_pi-setup](0_pi-setup/initial-setup.md)
```
some links are missing the trailing number

2021-01-25 12:59 UTC, bwnstck commented on README.md
> +For setting up the sensor follow the instructions in [1_sensor-setup](sensor-setup/humidity-sensor-setup.md)
```suggestion
For setting up the sensor follow the instructions in [1_sensor-setup](1_sensor-setup/humidity-sensor-setup.md)
```

2021-01-26 12:13 UTC, terezaif approved these changes

2021-01-26 12:13 UTC, merged